jobs:
        
  - name: sampletest-manifest
    type: manifest
    steps:
      - IN: sampletest-image1
      #- TASK: managed
      - IN: triggertestsample1
      
  - name: sampletest-ecsdeploy
    type: deploy
    steps:
      - IN: sampletest-manifest
      - IN: sampletest-cluster
      - TASK: managed
        #deployMethod: upgrade
